data_dir: /home/pi/raingauge/data/
log_dir: /home/pi/raingauge/logs/
log_filename: log.txt
label_file: davis_label.csv
record_hours: 168
sample_duration_sec: 10
davis_duration_sec: 180
file_format: "wav"
resolution: "S32"
sampling_rate: "8000"
learning_rate: 0.001
stft_shape: [None, 1, 1025, 2657]
infer_model_dir: /home/pi/raingauge/model/
deployed_model_type: withcnn
infer_model_withoutcnn: seq_stft.hdf5
infer_model_withcnn: rain_stft.hdf5
seq_len: 1360000
csv_file_name: recorded_data_and_estimates.csv
interrupt_pin: 13
davis_log_interval_sec: 10 # max.value is 60
DB_writing_interval_min: 3 # use multiples of 3 only