data_dir: /home/pi/raingauge/data/
log_dir: /home/pi/raingauge/logs/
log_filename: log.txt
label_file: davis_label.csv
record_hours: 72
sample_duration_sec: 10
davis_duration_sec: 180
file_format: "wav"
resolution: "S32"
sampling_rate: "8000"
learning_rate: 0.001
stft_shape: [1, 1025, 2657]
model_dir: model
infer_model_dir: /home/pi/raingauge/model/
model_name: cnn.hdf5
infer_model_name: seq_stft.hdf5
seq_len: 1360000